apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx               # Matches pods in the ReplicaSet
  ports:
    - protocol: TCP
      port: 8080               # Service port
      targetPort: 80         # Pod's containerPort
  type: ClusterIP            # Internal access only (default)