apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
  initContainers:
    - name: wait-for-db
      image: busybox
      command: ['sh', '-c', 'until nc -z localhost 5432; do echo waiting for db; sleep 2; done;']
  containers:
    - name: app-db
      image: my-db
    - name: app-api
      image: my-api
