apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-replication-controller
  labels:
    env: dev
  annotations:
    rc-env: dev
spec:
  replicas: 3
  selector: # label selector to match the pods controlled by this replication controller
    web-app: web-nginx
  template:
    metadata:
      name: nginx # name of the pod created by this replication controller
      labels:
        web-app: web-nginx # label to match the pods controlled by this replication controller
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
